version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ankadc123
      - POSTGRES_DB=EventManagementDB
    restart: always
  postgres_admin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    restart: always
  server:
    container_name: appserver_graphql
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/EventManagementDB
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    restart: always